### ISSUE TITLE
Better break? [edit: adding stop / start buttons for setting breaks]

### ISSUE THREAD

**Issue by RaedsLab** [omidfi/moro#10]
I think an option to start and end breaks would be useful : 

You'd type a command when going on a break: 
`moro break start`
And then type a command when you're back from a break:
`moro break end`

**Comment by omidfi** [comment]
Hi @raedslab, thanks for taking the time to open an issue here. 
That could be useful. Shouldn't be too much work to get it done either. However one thing that made me make Moro was the fact thatO started timers on other time trackers amd forgot to stop them at the right time. 
That's why in my opinion having no start/stop could be a feature in itself. 

Right now when I'm leaving for a break I just add a note: 

```bash
$: moro note  nap time
```
And when I'm back, whenever I remember

```bash
$: bash nap took aboug 40 mintued
``` 
And at the end of the day I add the 
I guess this is less mental load for me, and I don't need

**Comment by omidfi** [comment]
Oh Github doesn't work well on phone :( 

I was saying this way the stressfull stop/start 

part is avoided. 

Anyway I love to make it as useful as possible for as many users as I can. So if you and others mention the same thing, we need to implement it.
