### ISSUE TITLE
Time goal per day

### ISSUE THREAD

**Issue by Flouss** [omidfi/moro#180]
- Adding the capability to set a time goal per day ( or a predefined one ).
- Add time left before achieving this goal in the report. (Could be displayed as time the user should checkout)

This feature could help to set a time goal to achieve or a time limit of work per day.

**Comment by omidfi** [comment]
Hello, 

Thanks for opening the issue. Please help me understand it better. 

Currently each user cab define a work day length, the default is 7.5 hours, and the dailystatus report shows how many hours are needed to call it a full day. 

How would that goal be different from that?

**Comment by Flouss** [comment]
The work day would be configurable. Keep 7.5 hours as default but give the possibility to change it.

The dailystatus does show the time left to a full day. But the status/report command doesn't.

**Comment by Flouss** [comment]
After checking on the code and how Hours per day setting is used, the first feature would be a duplicate.

So, the only request left is the time to a full day in the report.

**Comment by omidfi** [comment]
@Flouss glad you found out how to configure that. 

In the reports table we can add a new column that shows the comparison with set goal in +/- mode. So that with moro report --all: 

| Date | Work Hourse | Time to a full day |
 Jan 1 | 5 hours           |  -2.5 h.                    |

The name of the column might still need improvement, but something in the same line. 

I'm currently working on upgrading packages and node version. Any help with implementing this would be appreciated. 

But I can take it afterwards.

**Comment by Flouss** [comment]
@omidfi Since you've mentioned that the time to a full day is displayed in the daily status (status shown after starting a work session) and I was happy with that display I've just added the **should work until** to the single report.

I'm personally happy with this solution, but let me know if you still want to go with the column in the full report, I will gladly take a look at it

**Comment by omidfi** [comment]
Great, thanks! 

Merged #183 and also updated moro in npm. If you update your moro to 4.1.0 you should see the feature you added @Flouss  :heart:
