### ISSUE TITLE
I would ❤️ to see this turned into a project time tracker (a la Harvest sort of thing)

### ISSUE THREAD

**Issue by wakatara** [omidfi/moro#82]
Cause I was looking for one that wasn't over the top crazy and could just log things, though looking for a human readable text file format for recording (I use taskpaper and ledger... don't act surprised... =] ).

Anyhow, like it... my favourite part is the "Moro \o/"...

**Comment by omidfi** [comment]
Hi @wakatara! 
Thanks for showing some love :)

I'm not sure Moro is a good fit for a full blown task manager. As it's aimed for 9 to 5 jobs with flexible hours. 
We addes the notes feature, so that users can remember when they switched task during the day. 
But please go ahead and share your ideas as feature requests or pull requests. We'll see how it can stay simple, and satisfy your needs too. 

Omid

**Comment by wakatara** [comment]
Heya @omidfi !

Fair enough. =] 

I do need a proper project time tracker though, so lemme see if I can make the changes within moro's as PRs and if not I'll just use your stuff as a base and fork (Moar-o?... =p ). I wanted to do the thing in js and as a cli so this is definitely great as a base if I do. Will keep you posted!

**Comment by omidfi** [comment]
Cool :)
I think it doesn't exist in the JS world as far as I know. It would be
appreciated.

Take a look at other ecosystems, there are good examples like Time Strap,
task warior etc.

ti 6. kesäkuuta 2017 klo 9.37 Daryl Manning <notifications@github.com>
kirjoitti:
