### ISSUE TITLE
dump unformatted enteries as plain text

### ISSUE THREAD

**Issue by omidfi** [omidfi/moro#83]
or maybe csv, by a command

**Comment by fleischie** [comment]
Do you mean for a backup? Something like `moro dump sql|csv`?

`moro dump sql` should be straight forward (a la Django's sqldump command):
```
# create tables
CREATE TABLE "records" ("id" integer not null primary key autoincrement, "date" date, "start" time, "end" time, "breakDuration" integer);
CREATE TABLE "notes" ("id" integer not null primary key autoincrement, "date" date, "createdat" varchar(255), "note" text);

# insert data
INSERT INTO records VALUES(1, 2017-07-31, "09:30", "18:00", "60");
INSERT INTO notes VALUES(1, 2017-07-31, "14:00", "Customer X :: Kickoff Meeting");
...
```


`moro dump csv` is tricky because of the separate tables, possibly by specifying the target: `moro dump csv records|notes`. Then it would be:
```
id,date,start,end,breakDuration;
1,2017-07-31,09:30,18:00,60;
```
or
```
id,date,createdat,note;
1,2017-07-31,14:00,"Customer X :: Kickoff Meeting";
```


Other formats can follow: json, yaml, xml, etc. I'm smelling a plugin-based dumping system. 🐽

**Comment by omidfi** [comment]
I saw a new user, a colleague sitting right beside me :D, start using moro, and I think the help screen was overwhelming for him as is. So maybe we skip on this feature request to not complex things :)  

Talks to himself: no we can't just add features for no good reason :D
